spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    username: Ivanov
    password: Ivanov

  # Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  cache:
    cache-names: users,restaurants,dishes
    caffeine.spec: maximumSize=1,expireAfterAccess=60s


logging:
  level:
    root: WARN
    ru.ivanov.restaurantvotingapplication: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

  #springdoc.swagger-ui.path:
